spring.application.name=demoCamel
camel.springboot.routes-collector-enabled=true
spring.activemq.broker-url=tcp://localhost:61616
camel.component.kafka.brokers = http://localhost:9092
server.port = 8081
sampleapi_port = http://localhost:8085
camel.springboot.tracing=true